"""empty message

Revision ID: 144c4eea7324
Revises: 
Create Date: 2020-07-27 11:15:40.457072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '144c4eea7324'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('balance', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts')
    # ### end Alembic commands ###
