"""empty message

Revision ID: 1fdea8e876a0
Revises: 144c4eea7324
Create Date: 2020-07-27 11:16:18.890020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fdea8e876a0'
down_revision = '144c4eea7324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'password')
    # ### end Alembic commands ###
