"""empty message

Revision ID: 3baee4783dcc
Revises: b4a5dd3d9dac
Create Date: 2020-07-28 00:11:14.199734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3baee4783dcc'
down_revision = 'b4a5dd3d9dac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('accounts', 'salt',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'salt',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('accounts', 'key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
