"""empty message

Revision ID: aab43e821e31
Revises: 3baee4783dcc
Create Date: 2020-07-28 00:32:02.400844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab43e821e31'
down_revision = '3baee4783dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('accounts', 'salt',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'salt',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('accounts', 'key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
